# .github/workflows/ci.yml
name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치 (v18)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 의존성 설치
        run: npm ci

      - name: 유닛 테스트 실행
        run: npm test

      - name: 린트 검사
        run: npm run lint

      - name: 타입스크립트 체크
        run: npm run typecheck

      - name: 프로젝트 빌드
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Vercel CLI 설치
        run: npm install -g vercel

      - name: Vercel 배포
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --token $VERCEL_TOKEN --confirm
